### ISSUE TITLE
buttons look weird?

### ISSUE THREAD

**Issue by fenwick67** [fenwick67/mastofeed#13]
remove this styling, not sure why it's there:

```css
label{
-webkit-appearance: push-button;
  -moz-appearance: button;
}
```
